"""Add description to receipts

Revision ID: 19794ba11a35
Revises: 5dc528f0a3c2
Create Date: 2026-04-15 20:30:31.482935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19794ba11a35'
down_revision: Union[str, Sequence[str], None] = '5dc528f0a3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'description')
    # ### end Alembic commands ###
