"""add_zoho_merchant_id_to_vendor

Revision ID: 3c89c79372de
Revises: 6df3574cff32
Create Date: 2026-04-21 15:15:05.807852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c89c79372de'
down_revision: Union[str, Sequence[str], None] = '6df3574cff32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('zoho_merchant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_vendors_zoho_merchant_id'), 'vendors', ['zoho_merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_zoho_merchant_id'), table_name='vendors')
    op.drop_column('vendors', 'zoho_merchant_id')
    # ### end Alembic commands ###
