"""Add category learning table

Revision ID: 5dc528f0a3c2
Revises: 012efb6d5989
Create Date: 2026-04-14 21:47:59.249633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc528f0a3c2'
down_revision: Union[str, Sequence[str], None] = '012efb6d5989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_learnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'keyword', 'category_id', name='_user_keyword_category_uc')
    )
    op.create_index(op.f('ix_category_learnings_id'), 'category_learnings', ['id'], unique=False)
    op.create_index(op.f('ix_category_learnings_keyword'), 'category_learnings', ['keyword'], unique=False)
    op.create_index(op.f('ix_category_learnings_user_id'), 'category_learnings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_learnings_user_id'), table_name='category_learnings')
    op.drop_index(op.f('ix_category_learnings_keyword'), table_name='category_learnings')
    op.drop_index(op.f('ix_category_learnings_id'), table_name='category_learnings')
    op.drop_table('category_learnings')
    # ### end Alembic commands ###
