"""add_indexes_for_performance

Revision ID: 6df3574cff32
Revises: 19794ba11a35
Create Date: 2026-04-18 00:16:17.518179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df3574cff32'
down_revision: Union[str, Sequence[str], None] = '19794ba11a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_line_items_category_id'), 'line_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_line_items_receipt_id'), 'line_items', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_receipts_main_category_id'), 'receipts', ['main_category_id'], unique=False)
    op.create_index(op.f('ix_receipts_status'), 'receipts', ['status'], unique=False)
    op.create_index(op.f('ix_receipts_vendor_id'), 'receipts', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_vendor_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_status'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_main_category_id'), table_name='receipts')
    op.drop_index(op.f('ix_line_items_receipt_id'), table_name='line_items')
    op.drop_index(op.f('ix_line_items_category_id'), table_name='line_items')
    # ### end Alembic commands ###
