"""Add track_line_items to Receipt

Revision ID: 86f3cb5a7508
Revises: 0dc6d38c160d
Create Date: 2026-04-12 23:33:21.138876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f3cb5a7508'
down_revision: Union[str, Sequence[str], None] = '0dc6d38c160d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
